TILES = {
    TILE_GRASS_1_LE: 1,
    TILE_GRASS_1:  2,
    TILE_GRASS_1_RE: 3,
    TILE_SKY_1:  10,
    TILE_SOLID: 11,
    TILE_EMPTY: 12,
    TILE_TREE_1_TOP: 21,
    TILE_TREE_1_BOTTOM: 31,
    TILE_BACKGROUND_HILL_1: 53,
    TILE_BACKGROUND_HILL_2: 54,
    TILE_BACKGROUND_HILL_3: 61,
    TILE_BACKGROUND_HILL_4: 62,
    TILE_BACKGROUND_HILL_5: 63,
    TILE_BACKGROUND_HILL_6: 64,
    TILE_MIDDLEGROUND_HILL_1: 72,
    TILE_MIDDLEGROUND_HILL_2: 73,
    TILE_MIDDLEGROUND_HILL_3: 74,
    TILE_MIDDLEGROUND_HILL_4: 81,
    TILE_MIDDLEGROUND_HILL_5: 82,
    TILE_MIDDLEGROUND_HILL_6: 83,
    TILE_MIDDLEGROUND_HILL_7: 84,
    TILE_MIDDLEGROUND_HILL_8: 85
}

for(const [key, value] of Object.entries(TILES)) {
    window[key] = value;
  }