
const UNIT_PLACEHOLDER_RADIUS = 5;
const MOVE_RATE_PIXELS = 2;
const MAX_DIST_FROM_WALK_TARGET = 100;

const PLAY_AREA_MARGIN = UNIT_PLACEHOLDER_RADIUS +3;
const TOP_MARGIN = 40;

const PEN_HEIGHT = 400; //50;
const PEN_SIDE_GAP = 2;
const PEN_BASE_GAP = 2;
const PEN_INNER_GAP = 1; //100;