#+TITLE: Gonzalo's Devlog

I'll try keeping a (public) journal of my gamedev activities (and related
stuff, like pixel art) here.
This is mainly for my own, to keep record of my journey as I learn and
create my own things, but I also hope it helps whoever reads it :)

* 2020
** 2020-03 marzo
*** 2020-03-12 jueves
	- <2020-03-12 jue 11:31> Worked a bit on "Bundle of 30 Language
      Games" this morning, moving game objects into an array and
      changing the title screen code to pull data from the game
      objects for drawing the game selection grid. Next time I'll work
      on refactoring ~handleGameCellClicks~ itself.
*** 2020-03-17 martes
- <2020-03-17 mar 09:43> Did some minor clean-up on "Bundle of 30
  Language Games", and found another good place to refactor:
  ~defineXAndYCoordinatesForTargets~ in
  PromptAndAnswerManager.js. Also made the shooter game load again,
  but it doesn't seem to run as it should.
*** 2020-03-27 viernes
- <2020-03-27 vie 19:11> Finished the (basic) tilesheet work on Turbo
  Racing. This allows me to move forward with the actual book
  exercises! I'll probably spend some time doing a couple of themes,
  rather than just the day/night tile sets suggested in the book, to
  get more pixel art practice.
** 2020-04 abril
*** 2020-04-08 miércoles
- <2020-04-08 mié 16:33> Got my runner in "Bundle of 30 Language
  Games" to jump again!
- <2020-04-08 mié 17:39> Bundle of 30 Language Games: Started work on
  integrating prompts and answers into my runner game. Made good
  progress, but there's still some bugs I'll need to fix.
*** 2020-04-13 lunes
- <2020-04-13 lun 08:07> Started work on Turbo Racing themes. I keep
  finding small bits to refactor. Must resist the temptation! I still
  need to make a lot of tile themes, that'll be good pixel art
  practice :)
