#+TITLE: Gonzalo's Devlog

I'll try keeping a (public) journal of my gamedev activities (and related
stuff, like pixel art) here.
This is mainly for my own, to keep record of my journey as I learn and
create my own things, but I also hope it helps whoever reads it :)

* 2020
** 2020-03 marzo
*** 2020-03-12 jueves
	- <2020-03-12 jue 11:31> Worked a bit on "Bundle of 30 Language
      Games" this morning, moving game objects into an array and
      changing the title screen code to pull data from the game
      objects for drawing the game selection grid. Next time I'll work
      on refactoring ~handleGameCellClicks~ itself.
*** 2020-03-17 martes
- <2020-03-17 mar 09:43> Did some minor clean-up on "Bundle of 30
  Language Games", and found another good place to refactor:
  ~defineXAndYCoordinatesForTargets~ in
  PromptAndAnswerManager.js. Also made the shooter game load again,
  but it doesn't seem to run as it should.
*** 2020-03-27 viernes
- <2020-03-27 vie 19:11> Finished the (basic) tilesheet work on Turbo
  Racing. This allows me to move forward with the actual book
  exercises! I'll probably spend some time doing a couple of themes,
  rather than just the day/night tile sets suggested in the book, to
  get more pixel art practice.
** 2020-04 abril
*** 2020-04-08 miércoles
- <2020-04-08 mié 16:33> Got my runner in "Bundle of 30 Language
  Games" to jump again!
- <2020-04-08 mié 17:39> Bundle of 30 Language Games: Started work on
  integrating prompts and answers into my runner game. Made good
  progress, but there's still some bugs I'll need to fix.
*** 2020-04-13 lunes
- <2020-04-13 lun 08:07> Started work on Turbo Racing themes. I keep
  finding small bits to refactor. Must resist the temptation! I still
  need to make a lot of tile themes, that'll be good pixel art
  practice :)
*** 2020-04-29 miércoles
- <2020-04-29 mié 09:41> (yesterday) did a little work on "Bundle of
  30 Language Games", fixing a bug in the runner game where sliding
  while jumping was possible (which got the runner "stuck" in the
  mid-air), and also tweaked the gravity and jump speed for a better
  jump feel.
** 2020-05 mayo
*** 2020-05-15 viernes
- <2020-05-15 vie 10:10> Added "Celeste" hair animation frame to "Xeno
  Jackers" player sprite. Tried to also add an anticipation frame to
  the jump animation, but couldn't crack it in the time I had.
*** 2020-05-21 jueves
- <2020-05-21 jue 06:41> Added a couple in-betweens to "Xeno Jackers"
  player landing animation, and also added a thumb-up animation (with
  some edits by Jeff, one of the leads). Really enjoying working on
  animations for that game!
*** 2020-05-26 martes
- <2020-05-26 mar 08:04> Started work on a very simple FSM for "Xeno
  Jackers". Hoping this will at least help get clarity on the states
  and transitions the player and other entities will be involved in
  during gameplay.
** 2020-06 junio
*** 2020-06-12 viernes
- <2020-06-12 vie 08:08> I finally "released" the FSM for Xeno
  Jackers. I like my simple code implementation, but ended up causing
  a lot of bugs and it seems it slowed down development for about a
  week, but happily H fixed a lot of the nastier bugs and the project
  is back on track.
